services:
  react-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src # Only mount the source code for hot reloading
      - ./public:/usr/src/app/public # Only mount the source code for hot reloading
      - ./index.html:/usr/src/app/index.html
      # - /usr/src/app/node_modules # Use a volume to avoid overriding the node_modules directory
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
