services:
  app:
    build: ./backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload --log-config backend/log_conf.yml
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - backend/.env
    environment:
      - MONGO_HOST=mongo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example_IbLEpHISturb
    volumes:
      - ./backend:/usr/backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example_IbLEpHISturb

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host 0.0.0.0 --port 5173
