services:
  vacal-backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example_IbLEpHISturb


  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example_IbLEpHISturb


  pytest_mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example_IbLEpHISturb
    tmpfs:
      - /data/db
    restart: "no"


  pytest:
    build:
      context: .
      dockerfile: pytest.Dockerfile
    depends_on:
      - pytest_mongo
    environment:
      - MONGO_HOST=pytest_mongo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example_IbLEpHISturb


