name: Frontend - Test Pull Requests

permissions:
  contents: read

on:
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: frontend

    - name: Run frontend tests
      run: npm test -- --run
      working-directory: frontend
